# Performance measurements of SMLT from Existing dataset

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import library packages
import pandas as p
import numpy as n

In [3]:
datae = p.read_csv("heart.csv")
df=datae.dropna()

In [4]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [5]:
#According to the cross-validated MCC scores, the random forest is the best-performing model, so now let's evaluate its performance on the test set.
from sklearn.metrics import confusion_matrix, classification_report, matthews_corrcoef, cohen_kappa_score, accuracy_score, average_precision_score, roc_auc_score

In [6]:
X = df.drop(labels='target', axis=1)
#Response variable
y = df.loc[:,'target']    

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

Logistic Regression :

In [8]:
from sklearn.linear_model import LogisticRegression
logR= LogisticRegression()

logR.fit(X_train,y_train)

predictR = logR.predict(X_test)

print("")
print('Classification report of Logistic Regression Results:')
print("")

print(classification_report(y_test,predictR))
xl = (accuracy_score(y_test,predictR)*100)

print('Accuracy result of Logistic Regression is:', xl)
print("")
cm1=confusion_matrix(y_test,predictR)
print('Confusion Matrix result of Logistic Regression is:\n',cm1)
print("")
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)
print("")



Classification report of Logistic Regression Results:

              precision    recall  f1-score   support

           0       0.85      0.85      0.85        41
           1       0.88      0.88      0.88        50

    accuracy                           0.87        91
   macro avg       0.87      0.87      0.87        91
weighted avg       0.87      0.87      0.87        91

Accuracy result of Logistic Regression is: 86.81318681318682

Confusion Matrix result of Logistic Regression is:
 [[35  6]
 [ 6 44]]

Sensitivity :  0.8536585365853658

Specificity :  0.88



Decision Tree Classifier :

In [9]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

dtree.fit(X_train, y_train)

predictDT = dtree.predict(X_test)

print("")
print('Classification report of Decision Tree Classifier Results:')
print("")

print(classification_report(y_test,predictDT))
xd = (accuracy_score(y_test,predictDT)*100)

print('Accuracy result of Decision Tree Classifier is', xd)
print("")
cm2=confusion_matrix(y_test,predictDT)
print('Confusion Matrix result of Decision Tree Classifier is:\n', confusion_matrix(y_test,predictDT))
print("")

sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1])
print('Specificity : ', specificity1)


Classification report of Decision Tree Classifier Results:

              precision    recall  f1-score   support

           0       0.70      0.80      0.75        41
           1       0.82      0.72      0.77        50

    accuracy                           0.76        91
   macro avg       0.76      0.76      0.76        91
weighted avg       0.77      0.76      0.76        91

Accuracy result of Decision Tree Classifier is 75.82417582417582

Confusion Matrix result of Decision Tree Classifier is:
 [[33  8]
 [14 36]]

Sensitivity :  0.8048780487804879

Specificity :  0.72


Random Forest:

In [10]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

rfc.fit(X_train,y_train)

predictR = rfc.predict(X_test)

print("")
print('Classification report of Random Forest Results:')
print("")

print(classification_report(y_test,predictR))
xr = (accuracy_score(y_test,predictR)*100)

print('Accuracy result of Random Forest is:', xr)
print("")
cm1=confusion_matrix(y_test,predictR)
print('Confusion Matrix result of Random Forest is:\n',cm1)
print("")
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)
print("")


Classification report of Random Forest Results:

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        41
           1       0.84      0.84      0.84        50

    accuracy                           0.82        91
   macro avg       0.82      0.82      0.82        91
weighted avg       0.82      0.82      0.82        91

Accuracy result of Random Forest is: 82.41758241758241

Confusion Matrix result of Random Forest is:
 [[33  8]
 [ 8 42]]

Sensitivity :  0.8048780487804879

Specificity :  0.84



Support Vector Machines:

In [11]:
from sklearn.svm import SVC
s = SVC()

s.fit(X_train,y_train)

predicts = s.predict(X_test)

print("")
print('Classification report of Support Vector Machines Results:')
print("")

print(classification_report(y_test,predicts))
xs = (accuracy_score(y_test,predicts)*100)

print('Accuracy result of Support Vector Machines is:', xs)
print("")
cm2=confusion_matrix(y_test,predicts)
print('Confusion Matrix result of Support Vector Machines is:\n',cm2)
print("")
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1])
print('Specificity : ', specificity1)
print("")


Classification report of Support Vector Machines Results:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        41
           1       0.55      1.00      0.71        50

    accuracy                           0.55        91
   macro avg       0.27      0.50      0.35        91
weighted avg       0.30      0.55      0.39        91

Accuracy result of Support Vector Machines is: 54.94505494505495

Confusion Matrix result of Support Vector Machines is:
 [[ 0 41]
 [ 0 50]]

Sensitivity :  0.0

Specificity :  1.0



Naive Bayes:

In [12]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train,y_train)

predictR = gnb.predict(X_test)

print("")
print('Classification report of Naive Bayes Results:')
print("")

print(classification_report(y_test,predictR))
xn = (accuracy_score(y_test,predictR)*100)

print('Accuracy result of Naive Bayes is:', xn)
print("")
cm1=confusion_matrix(y_test,predictR)
print('Confusion Matrix result of Naive Bayes is:\n',cm1)
print("")
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)
print("")


Classification report of Naive Bayes Results:

              precision    recall  f1-score   support

           0       0.80      0.78      0.79        41
           1       0.82      0.84      0.83        50

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91

Accuracy result of Naive Bayes is: 81.31868131868131

Confusion Matrix result of Naive Bayes is:
 [[32  9]
 [ 8 42]]

Sensitivity :  0.7804878048780488

Specificity :  0.84



K-Nearest Neighbor:

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knnc = KNeighborsClassifier()

knnc.fit(X_train,y_train)

predictR = knnc.predict(X_test)

print("")
print('Classification report of K-Nearest Neighbor Results:')
print("")

print(classification_report(y_test,predictR))
xk = (accuracy_score(y_test,predictR)*100)

print('Accuracy result of K-Nearest Neighbor is:', xk)
print("")
cm2=confusion_matrix(y_test,predictR)
print('Confusion Matrix result of K-Nearest Neighbor is:\n',cm2)
print("")
sensitivity1 = cm2[0,0]/(cm2[0,0]+cm2[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm2[1,1]/(cm2[1,0]+cm2[1,1])
print('Specificity : ', specificity1)
print("")


Classification report of K-Nearest Neighbor Results:

              precision    recall  f1-score   support

           0       0.63      0.59      0.61        41
           1       0.68      0.72      0.70        50

    accuracy                           0.66        91
   macro avg       0.66      0.65      0.65        91
weighted avg       0.66      0.66      0.66        91

Accuracy result of K-Nearest Neighbor is: 65.93406593406593

Confusion Matrix result of K-Nearest Neighbor is:
 [[24 17]
 [14 36]]

Sensitivity :  0.5853658536585366

Specificity :  0.72



In [14]:
def graph():
    import matplotlib.pyplot as plt
    data=[xl,xd,xr,xs,xn,xk]
    alg="LR","DT","RF","SVM","NB","KNN"
    plt.figure(figsize=(10,5))
    b=plt.bar(alg,data,color=("r","g","b","y","m","black"))
    plt.title("Heart disease of Accuracy score for Existing Datas",fontsize=15)
    plt.legend(b,data,fontsize=12)
    plt.savefig('Existing.png')

In [15]:
graph()

In [ ]:
import tkinter
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, NavigationToolbar2Tk)
from matplotlib.backend_bases import key_press_handler
from matplotlib.figure import Figure
import numpy as np
root = tkinter.Tk()
root.wm_title("Heart disease of Accuracy score for Existing Datas")
fig = Figure(figsize=(10,10),dpi=1)
canvas = FigureCanvasTkAgg(fig, master=root)  
canvas.draw()
canvas.get_tk_widget().pack(side=tkinter.TOP, fill=tkinter.BOTH, expand=1)
icon=tkinter.PhotoImage(file='Existing.png')   
label=tkinter.Label(root,image=icon)
label.pack()
root.mainloop()